github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end
title: JAVA Advanced (31089/1607/1819/1/72)
layout: single
author: David D'Haese
toc: true
toc_label: "My Custom Table of Contents Label"
toc_icon: "gear"